"""payment plan_id

Revision ID: b49b9de64f06
Revises: 95c8ee09af1b
Create Date: 2026-09-26 08:17:55.842723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49b9de64f06'
down_revision: Union[str, None] = '95c8ee09af1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


plans_table = sa.table(
    "plans",
    sa.column("code", sa.String),
    sa.column("name", sa.String),
    sa.column("price", sa.Numeric),
    sa.column("duration_days", sa.Integer),
    sa.column("flags", sa.JSON),
    sa.column("is_active", sa.Boolean),
)

admin_roles_table = sa.table(
    "admin_roles",
    sa.column("name", sa.String),
    sa.column("permissions", sa.JSON),
)

admin_users_table = sa.table(
    "admin_users",
    sa.column("username", sa.String),
    sa.column("password_hash", sa.String),
    sa.column("role_id", sa.Integer),
    sa.column("is_active", sa.Boolean),
    sa.column("is_2fa_enabled", sa.Boolean),
)

PLANS = [
    {
        "code": "starter",
        "name": "Starter",
        "price": 49000,
        "duration_days": 30,
        "flags": {
            "account_limit": 1,
            "max_bio_items": 2,
            "scheduler_limit": 3,
            "online_service": False,
            "emoji_service": False,
        },
    },
    {
        "code": "pro",
        "name": "Pro",
        "price": 149000,
        "duration_days": 30,
        "flags": {
            "account_limit": 5,
            "max_bio_items": 10,
            "scheduler_limit": 20,
            "online_service": True,
            "emoji_service": True,
        },
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("plan_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_payments_plan_id_plans", "payments", "plans", ["plan_id"], ["id"])
    # ### end Alembic commands ###

    op.bulk_insert(
        plans_table,
        [{**p, "is_active": True} for p in PLANS],
    )

    conn = op.get_bind()
    conn.execute(admin_roles_table.insert().values(name="SUPER_ADMIN", permissions={"all": True}))
    role_id = conn.execute(sa.text("SELECT id FROM admin_roles WHERE name = 'SUPER_ADMIN'")).scalar_one()
    conn.execute(
        admin_users_table.insert().values(
            username="admin",
            password_hash="",  # PHASE 9'da haqiqiy hash bilan almashtiriladi
            role_id=role_id,
            is_active=True,
            is_2fa_enabled=False,
        )
    )


def downgrade() -> None:
    op.execute(admin_users_table.delete().where(admin_users_table.c.username == "admin"))
    op.execute(admin_roles_table.delete().where(admin_roles_table.c.name == "SUPER_ADMIN"))
    op.execute(plans_table.delete().where(plans_table.c.code.in_([p["code"] for p in PLANS])))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_payments_plan_id_plans", "payments", type_="foreignkey")
    op.drop_column("payments", "plan_id")
    # ### end Alembic commands ###
