"""playlist selection strategy

Revision ID: bb933d0f1c2b
Revises: d9055dabddf1
Create Date: 2026-09-26 07:43:44.223219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb933d0f1c2b'
down_revision: Union[str, None] = 'd9055dabddf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SERVICES = [
    ("clock_name", "Clock Name", "Ismda joriy vaqtni ko'rsatib turadi"),
    ("auto_bio", "Auto Bio", "Bio maydonini shablon bo'yicha avtomatik yangilaydi"),
    ("auto_name", "Auto Name", "Ism maydonini shablon bo'yicha avtomatik yangilaydi"),
    ("playlist", "Name/Bio Playlist", "Bir nechta shablon orasida ketma-ket/tasodifiy almashadi"),
    ("combo", "Combo", "Bir nechta fieldni (name, bio, ...) birgalikda boshqaradi"),
    ("scenario", "Scenario", "Vaqt oralig'i (window) bo'yicha ishlaydigan avtomatlashtirish"),
]

services_table = sa.table(
    "services",
    sa.column("code", sa.String),
    sa.column("name", sa.String),
    sa.column("description", sa.Text),
    sa.column("is_active", sa.Boolean),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "automations",
        sa.Column(
            "selection_strategy",
            sa.Enum("NONE", "SEQUENTIAL", "RANDOM", name="selectionstrategy", native_enum=False, length=16),
            nullable=False,
            server_default="NONE",
        ),
    )
    op.add_column(
        "automations", sa.Column("last_playlist_index", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        services_table,
        [{"code": code, "name": name, "description": desc, "is_active": True} for code, name, desc in SERVICES],
    )


def downgrade() -> None:
    op.execute(sa.delete(services_table).where(services_table.c.code.in_([code for code, _, _ in SERVICES])))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("automations", "last_playlist_index")
    op.drop_column("automations", "selection_strategy")
    # ### end Alembic commands ###
